s = {'platformId': 4, 'AccountId': 'account.1768deae2ef04b97b6aa10162455504e',
     'Avatar': 'https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/1b/1b88cdb4c7a4486b0cc2d576d0c8cc3678bd128a.jpg',
     'selectedRegion': 'na', 'defaultSeason': '2017-pre3', 'seasonDisplay': 'Early Access Season #3',
     'LastUpdated': '2017-09-01T06:16:10.7770247Z', 'PlayerName': 'iabosi', 'PubgTrackerId': 763809, 'Stats': [
        {'Region': 'na', 'Season': '2017-pre3', 'Match': 'solo', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.62,
             'value': '1.62', 'rank': None, 'percentile': 30.0, 'displayValue': '1.62'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 2996.85, 'value': '2996.85', 'rank': None, 'percentile': 52.0, 'displayValue': '49m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 8,
             'ValueDec': None,
             'value': '8', 'rank': None, 'percentile': 34.0, 'displayValue': '8'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None, 'value': '0',
             'rank': 2701333, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Win Top 10 Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0, 'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 8, 'ValueDec': None,
             'value': '8',
             'rank': None, 'percentile': 34.0, 'displayValue': '8'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'Skill Rating', 'ValueInt': None, 'ValueDec': 1167.0,
             'value': '1167', 'rank': 2596008, 'percentile': 97.0, 'displayValue': '1,167'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1200.0, 'value': '1200', 'rank': None, 'percentile': 100.0, 'displayValue': '1,200'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 1590558,
             'ValueDec': None,
             'value': '1590558', 'rank': None, 'percentile': 15.0, 'displayValue': '1,590,558'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 208.86, 'value': '208.86', 'rank': None, 'percentile': 25.0, 'displayValue': '208.86'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.5, 'value': '0.5', 'rank': None, 'percentile': 20.0, 'displayValue': '0.50'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.38,
             'value': '0.38', 'rank': None, 'percentile': 67.0, 'displayValue': '0.38'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'PerGame', 'ValueInt': None, 'ValueDec': 1.62,
             'value': '1.62', 'rank': None, 'percentile': 30.0, 'displayValue': '1.62'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 756.92, 'value': '756.92', 'rank': None, 'percentile': 84.0, 'displayValue': '0.8km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Team Kills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.12,
             'value': '0.12', 'rank': None, 'percentile': 2.2, 'displayValue': '0.12'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 374.61, 'value': '374.61', 'rank': None, 'percentile': 90.0, 'displayValue': '6m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 13, 'ValueDec': None, 'value': '13',
             'rank': 675849, 'percentile': 30.0, 'displayValue': '13'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1',
             'rank': None, 'percentile': 9.0, 'displayValue': '1'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1', 'rank': None, 'percentile': 9.0, 'displayValue': '1'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 4, 'ValueDec': None,
             'value': '4', 'rank': None, 'percentile': 24.0, 'displayValue': '4'},
            {'label': 'Headshot Kill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.31, 'value': '0.31', 'rank': None, 'percentile': 17.0, 'displayValue': '0.31'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 6, 'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 29.0, 'displayValue': '6'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 6,
             'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 23.0, 'displayValue': '6'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 1,
             'ValueDec': None,
             'value': '1', 'rank': None, 'percentile': 81.0, 'displayValue': '1'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 6, 'ValueDec': None, 'value': '6',
             'rank': None, 'percentile': 20.0, 'displayValue': '6'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 650.77, 'value': '650.77', 'rank': None, 'percentile': 87.0, 'displayValue': '10m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 650.77, 'value': '650.77', 'rank': None, 'percentile': 87.0, 'displayValue': '10m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 374.61, 'value': '374.61', 'rank': None, 'percentile': 90.0, 'displayValue': '6m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 951, 'ValueDec': None,
             'value': '951', 'rank': 2701333, 'percentile': 99.0, 'displayValue': '951'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 3537.79, 'value': '3537.79', 'rank': None, 'percentile': 58.0, 'displayValue': '3.5km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 2517.58, 'value': '2517.58', 'rank': None, 'percentile': 59.0, 'displayValue': '2.5km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 6055.37, 'value': '6055.37', 'rank': None, 'percentile': 60.0, 'displayValue': '6.1km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 442.22, 'value': '442.22', 'rank': None, 'percentile': 87.0, 'displayValue': '0.4km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 314.7, 'value': '314.7', 'rank': None, 'percentile': 69.0, 'displayValue': '0.3km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 67.24,
             'value': '67.24', 'rank': None, 'percentile': 51.0, 'displayValue': '67.2m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 3, 'ValueDec': None, 'value': '3',
             'rank': None, 'percentile': 57.0, 'displayValue': '3'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 5, 'ValueDec': None, 'value': '5',
             'rank': None, 'percentile': 47.0, 'displayValue': '5'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 1670.88,
             'value': '1670.88', 'rank': None, 'percentile': 27.0, 'displayValue': '1,670.88'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'}]},
        {'Region': 'na', 'Season': '2017-pre3', 'Match': 'duo', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.67,
             'value': '1.67', 'rank': None, 'percentile': 25.0, 'displayValue': '1.67'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 6625.05, 'value': '6625.05', 'rank': None, 'percentile': 47.0, 'displayValue': '1h 50m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 6,
             'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 55.0, 'displayValue': '6'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None, 'value': '0',
             'rank': 658009, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Win Top 10 Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0, 'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 2, 'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 49.0, 'displayValue': '2'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 33.33,
             'value': '33.33', 'rank': None, 'percentile': 32.0, 'displayValue': '33.3%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 6, 'ValueDec': None,
             'value': '6',
             'rank': None, 'percentile': 54.0, 'displayValue': '6'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'Skill Rating', 'ValueInt': None, 'ValueDec': 1304.0,
             'value': '1304', 'rank': 647352, 'percentile': 40.0, 'displayValue': '1,304'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1326.7, 'value': '1326.7', 'rank': None, 'percentile': 37.0, 'displayValue': '1,327'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 393074,
             'ValueDec': None,
             'value': '393074', 'rank': None, 'percentile': 54.0, 'displayValue': '393,074'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 245.39, 'value': '245.39', 'rank': None, 'percentile': 19.0, 'displayValue': '245.39'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.5, 'value': '0.5', 'rank': None, 'percentile': 14.0, 'displayValue': '0.50'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 3.17,
             'value': '3.17', 'rank': None, 'percentile': 12.0, 'displayValue': '3.17'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.67,
             'value': '1.67', 'rank': None, 'percentile': 24.0, 'displayValue': '1.67'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 4648.18, 'value': '4648.18', 'rank': None, 'percentile': 15.0, 'displayValue': '4.6km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.33,
             'value': '0.33', 'rank': None, 'percentile': 14.0, 'displayValue': '0.33'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Team Kills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 1104.18, 'value': '1104.18', 'rank': None, 'percentile': 27.0, 'displayValue': '18m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.33,
             'value': '0.33', 'rank': None, 'percentile': 32.0, 'displayValue': '0.33'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 10, 'ValueDec': None, 'value': '10',
             'rank': 588255, 'percentile': 41.0, 'displayValue': '10'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 6, 'ValueDec': None,
             'value': '6',
             'rank': None, 'percentile': 24.0, 'displayValue': '6'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 3, 'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 32.0, 'displayValue': '3'},
            {'label': 'Headshot Kill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.3, 'value': '0.3', 'rank': None, 'percentile': 14.0, 'displayValue': '0.30'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 10, 'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 24.0, 'displayValue': '10'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 3,
             'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 55.0, 'displayValue': '3'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 57.0, 'displayValue': '2'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 2, 'ValueDec': None, 'value': '2',
             'rank': None, 'percentile': 60.0, 'displayValue': '2'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1896.95, 'value': '1896.95', 'rank': None, 'percentile': 25.0, 'displayValue': '31m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1896.95, 'value': '1896.95', 'rank': None, 'percentile': 25.0, 'displayValue': '31m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1104.18, 'value': '1104.18', 'rank': None, 'percentile': 27.0, 'displayValue': '18m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 1085, 'ValueDec': None,
             'value': '1085', 'rank': 658009, 'percentile': 40.0, 'displayValue': '1,085'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 9365.85, 'value': '9365.85', 'rank': None, 'percentile': 49.0, 'displayValue': '9.4km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 18523.25, 'value': '18523.25', 'rank': None, 'percentile': 34.0, 'displayValue': '18.5km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 27889.1, 'value': '27889.1', 'rank': None, 'percentile': 40.0, 'displayValue': '27.9km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 1560.98, 'value': '1560.98', 'rank': None, 'percentile': 35.0, 'displayValue': '1.6km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 3087.21, 'value': '3087.21', 'rank': None, 'percentile': 12.0, 'displayValue': '3.1km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 77.95,
             'value': '77.95', 'rank': None, 'percentile': 54.0, 'displayValue': '78.0m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 19, 'ValueDec': None, 'value': '19',
             'rank': None, 'percentile': 36.0, 'displayValue': '19'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 2, 'ValueDec': None,
             'value': '2',
             'rank': None, 'percentile': 38.0, 'displayValue': '2'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 10, 'ValueDec': None,
             'value': '10',
             'rank': None, 'percentile': 41.0, 'displayValue': '10'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 1472.35,
             'value': '1472.35', 'rank': None, 'percentile': 38.0, 'displayValue': '1,472.35'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 5, 'ValueDec': None,
             'value': '5',
             'rank': None, 'percentile': 47.0, 'displayValue': '5'}]},
        {'Region': 'na', 'Season': '2017-pre3', 'Match': 'squad', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.24,
             'value': '1.24', 'rank': None, 'percentile': 38.0, 'displayValue': '1.24'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 9.38,
             'value': '9.38', 'rank': None, 'percentile': 20.0, 'displayValue': '9.4%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 31550.43, 'value': '31550.43', 'rank': None, 'percentile': 22.0, 'displayValue': '8h 45m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 32,
             'ValueDec': None,
             'value': '32', 'rank': None, 'percentile': 23.0, 'displayValue': '32'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 3, 'ValueDec': None, 'value': '3',
             'rank': 224936, 'percentile': 16.0, 'displayValue': '3'},
            {'label': 'Win Top 10Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.21, 'value': '0.21', 'rank': None, 'percentile': 21.0, 'displayValue': '0.2%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 14, 'ValueDec': None,
             'value': '14', 'rank': None, 'percentile': 20.0, 'displayValue': '14'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 43.75,
             'value': '43.75', 'rank': None, 'percentile': 39.0, 'displayValue': '43.8%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 29, 'ValueDec': None,
             'value': '29', 'rank': None, 'percentile': 23.0, 'displayValue': '29'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'Skill Rating', 'ValueInt': None, 'ValueDec': 1544.0,
             'value': '1544', 'rank': 223937, 'percentile': 17.0, 'displayValue': '1,544'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1543.56, 'value': '1543.56', 'rank': None, 'percentile': 19.0, 'displayValue': '1,544'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 107789,
             'ValueDec': None,
             'value': '107789', 'rank': None, 'percentile': 73.0, 'displayValue': '107,789'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 198.78, 'value': '198.78', 'rank': None, 'percentile': 29.0, 'displayValue': '198.78'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.31, 'value': '0.31', 'rank': None, 'percentile': 21.0, 'displayValue': '0.31'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.94,
             'value': '1.94', 'rank': None, 'percentile': 41.0, 'displayValue': '1.94'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.12,
             'value': '1.12', 'rank': None, 'percentile': 40.0, 'displayValue': '1.12'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 3513.48, 'value': '3513.48', 'rank': None, 'percentile': 39.0, 'displayValue': '3.5km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.25,
             'value': '0.25', 'rank': None, 'percentile': 35.0, 'displayValue': '0.25'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Team Kills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.09,
             'value': '0.09', 'rank': None, 'percentile': 7.0, 'displayValue': '0.09'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 985.95, 'value': '985.95', 'rank': None, 'percentile': 48.0, 'displayValue': '16m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.44,
             'value': '0.44', 'rank': None, 'percentile': 39.0, 'displayValue': '0.44'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 36, 'ValueDec': None, 'value': '36',
             'rank': 249268, 'percentile': 22.0, 'displayValue': '36'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 21, 'ValueDec': None,
             'value': '21',
             'rank': None, 'percentile': 13.0, 'displayValue': '21'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1',
             'rank': None, 'percentile': 13.0, 'displayValue': '1'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 3, 'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 7.0, 'displayValue': '3'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 10,
             'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 14.0, 'displayValue': '10'},
            {'label': 'Headshot Kill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.28, 'value': '0.28', 'rank': None, 'percentile': 13.0, 'displayValue': '0.28'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 9.0, 'displayValue': '2'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 10,
             'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 6.0, 'displayValue': '10'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 59.0, 'displayValue': '2'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 6, 'ValueDec': None, 'value': '6',
             'rank': None, 'percentile': 26.0, 'displayValue': '6'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 2028.42, 'value': '2028.42', 'rank': None, 'percentile': 7.0, 'displayValue': '33m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 2028.42, 'value': '2028.42', 'rank': None, 'percentile': 7.0, 'displayValue': '33m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 985.95, 'value': '985.95', 'rank': None, 'percentile': 48.0, 'displayValue': '16m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 1287, 'ValueDec': None,
             'value': '1287', 'rank': 224936, 'percentile': 17.0, 'displayValue': '1,287'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 44037.44, 'value': '44037.44', 'rank': None, 'percentile': 24.0, 'displayValue': '44.0km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 68393.8, 'value': '68393.8', 'rank': None, 'percentile': 18.0, 'displayValue': '68.4km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 112431.2, 'value': '112431.2', 'rank': None, 'percentile': 20.0, 'displayValue': '112.4km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 1376.17, 'value': '1376.17', 'rank': None, 'percentile': 60.0, 'displayValue': '1.4km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 2137.31, 'value': '2137.31', 'rank': None, 'percentile': 30.0, 'displayValue': '2.1km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 390.86,
             'value': '390.86', 'rank': None, 'percentile': 6.0, 'displayValue': '390.9m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 62, 'ValueDec': None, 'value': '62',
             'rank': None, 'percentile': 21.0, 'displayValue': '62'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 8, 'ValueDec': None,
             'value': '8',
             'rank': None, 'percentile': 21.0, 'displayValue': '8'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 39, 'ValueDec': None,
             'value': '39',
             'rank': None, 'percentile': 21.0, 'displayValue': '39'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 6361.05,
             'value': '6361.05', 'rank': None, 'percentile': 18.0, 'displayValue': '6,361.05'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 36, 'ValueDec': None,
             'value': '36', 'rank': None, 'percentile': 21.0, 'displayValue': '36'}]},
        {'Region': 'agg', 'Season': '2017-pre3', 'Match': 'solo', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.62,
             'value': '1.62', 'rank': None, 'percentile': 29.0, 'displayValue': '1.62'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 2996.85, 'value': '2996.85', 'rank': None, 'percentile': 86.0, 'displayValue': '49m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 8,
             'ValueDec': None,
             'value': '8', 'rank': None, 'percentile': 73.0, 'displayValue': '8'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None, 'value': '0',
             'rank': 2701333, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Win Top 10 Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0, 'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 8, 'ValueDec': None,
             'value': '8',
             'rank': None, 'percentile': 72.0, 'displayValue': '8'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'SkillRating', 'ValueInt': None, 'ValueDec': 1167.0,
             'value': '1167', 'rank': 2596008, 'percentile': 99.0, 'displayValue': '1,167'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1200.0, 'value': '1200', 'rank': None, 'percentile': 100.0, 'displayValue': '1,200'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 208.86, 'value': '208.86', 'rank': None, 'percentile': 22.0, 'displayValue': '208.86'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.5, 'value': '0.5', 'rank': None, 'percentile': 16.0, 'displayValue': '0.50'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.38,
             'value': '0.38', 'rank': None, 'percentile': 87.0, 'displayValue': '0.38'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.62,
             'value': '1.62', 'rank': None, 'percentile': 27.0, 'displayValue': '1.62'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 756.92, 'value': '756.92', 'rank': None, 'percentile': 96.0, 'displayValue': '0.8km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'TeamKills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.12,
             'value': '0.12', 'rank': None, 'percentile': 1.5, 'displayValue': '0.12'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 374.61, 'value': '374.61', 'rank': None, 'percentile': 98.0, 'displayValue': '6m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 13, 'ValueDec': None, 'value': '13',
             'rank': 675849, 'percentile': 67.0, 'displayValue': '13'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1',
             'rank': None, 'percentile': 24.0, 'displayValue': '1'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1', 'rank': None, 'percentile': 24.0, 'displayValue': '1'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 4, 'ValueDec': None,
             'value': '4', 'rank': None, 'percentile': 57.0, 'displayValue': '4'},
            {'label': 'Headshot Kill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.31, 'value': '0.31', 'rank': None, 'percentile': 13.0, 'displayValue': '0.31'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 6, 'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 57.0, 'displayValue': '6'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 6,
             'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 45.0, 'displayValue': '6'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 1,
             'ValueDec': None,
             'value': '1', 'rank': None, 'percentile': 95.0, 'displayValue': '1'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 6, 'ValueDec': None, 'value': '6',
             'rank': None, 'percentile': 58.0, 'displayValue': '6'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 650.77, 'value': '650.77', 'rank': None, 'percentile': 98.0, 'displayValue': '10m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 650.77, 'value': '650.77', 'rank': None, 'percentile': 98.0, 'displayValue': '10m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 374.61, 'value': '374.61', 'rank': None, 'percentile': 98.0, 'displayValue': '6m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 951, 'ValueDec': None,
             'value': '951', 'rank': 2701333, 'percentile': 100.0, 'displayValue': '951'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 3537.79, 'value': '3537.79', 'rank': None, 'percentile': 88.0, 'displayValue': '3.5km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 2517.58, 'value': '2517.58', 'rank': None, 'percentile': 85.0, 'displayValue': '2.5km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 6055.37, 'value': '6055.37', 'rank': None, 'percentile': 88.0, 'displayValue': '6.1km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 442.22, 'value': '442.22', 'rank': None, 'percentile': 96.0, 'displayValue': '0.4km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 314.7, 'value': '314.7', 'rank': None, 'percentile': 84.0, 'displayValue': '0.3km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 67.24,
             'value': '67.24', 'rank': None, 'percentile': 79.0, 'displayValue': '67.2m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 3, 'ValueDec': None, 'value': '3',
             'rank': None, 'percentile': 85.0, 'displayValue': '3'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 5, 'ValueDec': None, 'value': '5',
             'rank': None, 'percentile': 79.0, 'displayValue': '5'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 1670.88,
             'value': '1670.88', 'rank': None, 'percentile': 64.0, 'displayValue': '1,670.88'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'}]},
        {'Region': 'agg', 'Season': '2017-pre3', 'Match': 'duo', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.67,
             'value': '1.67', 'rank': None, 'percentile': 23.0, 'displayValue': '1.67'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 6625.05, 'value': '6625.05', 'rank': None, 'percentile': 82.0, 'displayValue': '1h 50m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 6,
             'ValueDec': None,
             'value': '6', 'rank': None, 'percentile': 86.0, 'displayValue': '6'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 0, 'ValueDec': None, 'value': '0',
             'rank': 658009, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Win Top 10 Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.0, 'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.0%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 2, 'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 81.0, 'displayValue': '2'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 33.3,
             'value': '33.3', 'rank': None, 'percentile': 28.0, 'displayValue': '33.3%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 6, 'ValueDec': None,
             'value': '6',
             'rank': None, 'percentile': 85.0, 'displayValue': '6'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'Skill Rating', 'ValueInt': None, 'ValueDec': 1304.0,
             'value': '1304', 'rank': 647352, 'percentile': 74.0, 'displayValue': '1,304'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1326.7, 'value': '1326.7', 'rank': None, 'percentile': 72.0, 'displayValue': '1,327'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 245.39, 'value': '245.39', 'rank': None, 'percentile': 15.0, 'displayValue': '245.39'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.5, 'value': '0.5', 'rank': None, 'percentile': 9.0, 'displayValue': '0.50'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 3.17,
             'value': '3.17', 'rank': None, 'percentile': 7.0, 'displayValue': '3.17'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.67,
             'value': '1.67', 'rank': None, 'percentile': 21.0, 'displayValue': '1.67'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 4648.18, 'value': '4648.18', 'rank': None, 'percentile': 10.0, 'displayValue': '4.6km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.33,
             'value': '0.33', 'rank': None, 'percentile': 7.0, 'displayValue': '0.33'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Team Kills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 1104.18, 'value': '1104.18', 'rank': None, 'percentile': 20.0, 'displayValue': '18m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.33,
             'value': '0.33', 'rank': None, 'percentile': 28.0, 'displayValue': '0.33'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 10, 'ValueDec': None, 'value': '10',
             'rank': 588255, 'percentile': 73.0, 'displayValue': '10'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 6, 'ValueDec': None,
             'value': '6',
             'rank': None, 'percentile': 56.0, 'displayValue': '6'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0',
             'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 3, 'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 63.0, 'displayValue': '3'},
            {'label': 'Headshot Kill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.3, 'value': '0.3', 'rank': None, 'percentile': 9.0, 'displayValue': '0.30'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 10, 'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 48.0, 'displayValue': '10'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 3,
             'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 79.0, 'displayValue': '3'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 81.0, 'displayValue': '2'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 2, 'ValueDec': None, 'value': '2',
             'rank': None, 'percentile': 89.0, 'displayValue': '2'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1896.95, 'value': '1896.95', 'rank': None, 'percentile': 51.0, 'displayValue': '31m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1896.95, 'value': '1896.95', 'rank': None, 'percentile': 51.0, 'displayValue': '31m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 1104.18, 'value': '1104.18', 'rank': None, 'percentile': 23.0, 'displayValue': '18m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 1085, 'ValueDec': None,
             'value': '1085', 'rank': 658009, 'percentile': 78.0, 'displayValue': '1,085'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 9365.85, 'value': '9365.85', 'rank': None, 'percentile': 83.0, 'displayValue': '9.4km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 18523.25, 'value': '18523.25', 'rank': None, 'percentile': 70.0, 'displayValue': '18.5km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 27889.1, 'value': '27889.1', 'rank': None, 'percentile': 76.0, 'displayValue': '27.9km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 1560.98, 'value': '1560.98', 'rank': None, 'percentile': 32.0, 'displayValue': '1.6km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 3087.21, 'value': '3087.21', 'rank': None, 'percentile': 9.0, 'displayValue': '3.1km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 77.95,
             'value': '77.95', 'rank': None, 'percentile': 78.0, 'displayValue': '78.0m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 19, 'ValueDec': None, 'value': '19',
             'rank': None, 'percentile': 71.0, 'displayValue': '19'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 2, 'ValueDec': None,
             'value': '2',
             'rank': None, 'percentile': 70.0, 'displayValue': '2'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 10, 'ValueDec': None,
             'value': '10',
             'rank': None, 'percentile': 74.0, 'displayValue': '10'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 1472.35,
             'value': '1472.35', 'rank': None, 'percentile': 72.0, 'displayValue': '1,472.35'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 5, 'ValueDec': None,
             'value': '5',
             'rank': None, 'percentile': 79.0, 'displayValue': '5'}]},
        {'Region': 'agg', 'Season': '2017-pre3', 'Match': 'squad', 'Stats': [
            {'label': 'K/D Ratio', 'field': 'KillDeathRatio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 1.24,
             'value': '1.24', 'rank': None, 'percentile': 34.0, 'displayValue': '1.24'},
            {'label': 'Win %', 'field': 'WinRatio', 'category': 'Performance', 'ValueInt': None, 'ValueDec': 9.38,
             'value': '9.38', 'rank': None, 'percentile': 16.0, 'displayValue': '9.4%'},
            {'label': 'Time Survived', 'field': 'TimeSurvived', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 31550.43, 'value': '31550.43', 'rank': None, 'percentile': 61.0, 'displayValue': '8h 45m '},
            {'label': 'Rounds Played', 'field': 'RoundsPlayed', 'category': 'Performance', 'ValueInt': 32,
             'ValueDec': None,
             'value': '32', 'rank': None, 'percentile': 62.0, 'displayValue': '32'},
            {'label': 'Wins', 'field': 'Wins', 'category': 'Performance', 'ValueInt': 3, 'ValueDec': None, 'value': '3',
             'rank': 224936, 'percentile': 43.0, 'displayValue': '3'},
            {'label': 'Win Top 10 Ratio', 'field': 'WinTop10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 0.21, 'value': '0.21', 'rank': None, 'percentile': 20.0, 'displayValue': '0.2%'},
            {'label': 'Top 10s', 'field': 'Top10s', 'category': 'Performance', 'ValueInt': 14, 'ValueDec': None,
             'value': '14', 'rank': None, 'percentile': 57.0, 'displayValue': '14'},
            {'label': 'Top 10 Rate', 'field': 'Top10Ratio', 'category': 'Performance', 'ValueInt': None,
             'ValueDec': 43.8,
             'value': '43.8', 'rank': None, 'percentile': 30.0, 'displayValue': '43.8%'},
            {'label': 'Losses', 'field': 'Losses', 'category': 'Performance', 'ValueInt': 29, 'ValueDec': None,
             'value': '29', 'rank': None, 'percentile': 63.0, 'displayValue': '29'},
            {'label': 'Rating', 'field': 'Rating', 'category': 'Skill Rating', 'ValueInt': None, 'ValueDec': 1544.0,
             'value': '1544', 'rank': 223937, 'percentile': 52.0, 'displayValue': '1,544'},
            {'label': 'Best Rating', 'field': 'BestRating', 'category': 'Skill Rating', 'ValueInt': None,
             'ValueDec': 1543.56, 'value': '1543.56', 'rank': None, 'percentile': 54.0, 'displayValue': '1,544'},
            {'label': 'Best Rank', 'field': 'BestRank', 'category': 'Skill Rating', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Avg Dmg per Match', 'field': 'DamagePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 198.78, 'value': '198.78', 'rank': None, 'percentile': 23.0, 'displayValue': '198.78'},
            {'label': 'Headshot Kills Pg', 'field': 'HeadshotKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.31, 'value': '0.31', 'rank': None, 'percentile': 14.0, 'displayValue': '0.31'},
            {'label': 'Heals Pg', 'field': 'HealsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.94,
             'value': '1.94', 'rank': None, 'percentile': 42.0, 'displayValue': '1.94'},
            {'label': 'Kills Pg', 'field': 'KillsPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 1.12,
             'value': '1.12', 'rank': None, 'percentile': 37.0, 'displayValue': '1.12'},
            {'label': 'Move Distance Pg', 'field': 'MoveDistancePg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 3513.48, 'value': '3513.48', 'rank': None, 'percentile': 34.0, 'displayValue': '3.5km'},
            {'label': 'Revives Pg', 'field': 'RevivesPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.25,
             'value': '0.25', 'rank': None, 'percentile': 29.0, 'displayValue': '0.25'},
            {'label': 'Road Kills Pg', 'field': 'RoadKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.0,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0.00'},
            {'label': 'Team Kills Pg', 'field': 'TeamKillsPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 0.09,
             'value': '0.09', 'rank': None, 'percentile': 6.0, 'displayValue': '0.09'},
            {'label': 'Time Survived Pg', 'field': 'TimeSurvivedPg', 'category': 'Per Game', 'ValueInt': None,
             'ValueDec': 985.95, 'value': '985.95', 'rank': None, 'percentile': 43.0, 'displayValue': '16m '},
            {'label': 'Top 10s Pg', 'field': 'Top10sPg', 'category': 'Per Game', 'ValueInt': None, 'ValueDec': 0.44,
             'value': '0.44', 'rank': None, 'percentile': 29.0, 'displayValue': '0.44'},
            {'label': 'Kills', 'field': 'Kills', 'category': 'Combat', 'ValueInt': 36, 'ValueDec': None, 'value': '36',
             'rank': 249268, 'percentile': 56.0, 'displayValue': '36'},
            {'label': 'Assists', 'field': 'Assists', 'category': 'Combat', 'ValueInt': 21, 'ValueDec': None,
             'value': '21',
             'rank': None, 'percentile': 43.0, 'displayValue': '21'},
            {'label': 'Suicides', 'field': 'Suicides', 'category': 'Combat', 'ValueInt': 1, 'ValueDec': None,
             'value': '1',
             'rank': None, 'percentile': 34.0, 'displayValue': '1'},
            {'label': 'Team Kills', 'field': 'TeamKills', 'category': 'Combat', 'ValueInt': 3, 'ValueDec': None,
             'value': '3', 'rank': None, 'percentile': 24.0, 'displayValue': '3'},
            {'label': 'Headshot Kills', 'field': 'HeadshotKills', 'category': 'Combat', 'ValueInt': 10,
             'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 41.0, 'displayValue': '10'},
            {'label': 'HeadshotKill Ratio', 'field': 'HeadshotKillRatio', 'category': 'Combat', 'ValueInt': None,
             'ValueDec': 0.28, 'value': '0.28', 'rank': None, 'percentile': 8.0, 'displayValue': '0.28'},
            {'label': 'Vehicle Destroys', 'field': 'VehicleDestroys', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 29.0, 'displayValue': '2'},
            {'label': 'Road Kills', 'field': 'RoadKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Daily Kills', 'field': 'DailyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Weekly Kills', 'field': 'WeeklyKills', 'category': 'Combat', 'ValueInt': 0, 'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Round Most Kills', 'field': 'RoundMostKills', 'category': 'Combat', 'ValueInt': 10,
             'ValueDec': None,
             'value': '10', 'rank': None, 'percentile': 13.0, 'displayValue': '10'},
            {'label': 'Max Kill Streaks', 'field': 'MaxKillStreaks', 'category': 'Combat', 'ValueInt': 2,
             'ValueDec': None,
             'value': '2', 'rank': None, 'percentile': 84.0, 'displayValue': '2'},
            {'label': 'Weapons Acquired', 'field': 'WeaponAcquired', 'category': 'Combat', 'ValueInt': 0,
             'ValueDec': None,
             'value': '0', 'rank': None, 'percentile': 100.0, 'displayValue': '0'},
            {'label': 'Days', 'field': 'Days', 'category': 'Survival', 'ValueInt': 6, 'ValueDec': None, 'value': '6',
             'rank': None, 'percentile': 64.0, 'displayValue': '6'},
            {'label': 'Longest Time Survived', 'field': 'LongestTimeSurvived', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 2028.42, 'value': '2028.42', 'rank': None, 'percentile': 18.0, 'displayValue': '33m '},
            {'label': 'Most Survival Time', 'field': 'MostSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 2028.42, 'value': '2028.42', 'rank': None, 'percentile': 18.0, 'displayValue': '33m '},
            {'label': 'Avg Survival Time', 'field': 'AvgSurvivalTime', 'category': 'Survival', 'ValueInt': None,
             'ValueDec': 985.95, 'value': '985.95', 'rank': None, 'percentile': 47.0, 'displayValue': '16m '},
            {'label': 'Win Points', 'field': 'WinPoints', 'category': 'Performance', 'ValueInt': 1287, 'ValueDec': None,
             'value': '1287', 'rank': 224936, 'percentile': 66.0, 'displayValue': '1,287'},
            {'label': 'Walk Distance', 'field': 'WalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 44037.44, 'value': '44037.44', 'rank': None, 'percentile': 63.0, 'displayValue': '44.0km'},
            {'label': 'Ride Distance', 'field': 'RideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 68393.8, 'value': '68393.8', 'rank': None, 'percentile': 54.0, 'displayValue': '68.4km'},
            {'label': 'Move Distance', 'field': 'MoveDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 112431.2, 'value': '112431.2', 'rank': None, 'percentile': 58.0, 'displayValue': '112.4km'},
            {'label': 'Avg Walk Distance', 'field': 'AvgWalkDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 1376.17, 'value': '1376.17', 'rank': None, 'percentile': 62.0, 'displayValue': '1.4km'},
            {'label': 'Avg Ride Distance', 'field': 'AvgRideDistance', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 2137.31, 'value': '2137.31', 'rank': None, 'percentile': 28.0, 'displayValue': '2.1km'},
            {'label': 'Longest Kill', 'field': 'LongestKill', 'category': 'Distance', 'ValueInt': None,
             'ValueDec': 390.86,
             'value': '390.86', 'rank': None, 'percentile': 14.0, 'displayValue': '390.9m'},
            {'label': 'Heals', 'field': 'Heals', 'category': 'Support', 'ValueInt': 62, 'ValueDec': None, 'value': '62',
             'rank': None, 'percentile': 58.0, 'displayValue': '62'},
            {'label': 'Revives', 'field': 'Revives', 'category': 'Support', 'ValueInt': 8, 'ValueDec': None,
             'value': '8',
             'rank': None, 'percentile': 56.0, 'displayValue': '8'},
            {'label': 'Boosts', 'field': 'Boosts', 'category': 'Support', 'ValueInt': 39, 'ValueDec': None,
             'value': '39',
             'rank': None, 'percentile': 57.0, 'displayValue': '39'},
            {'label': 'Damage Dealt', 'field': 'DamageDealt', 'category': 'Support', 'ValueInt': None,
             'ValueDec': 6361.05,
             'value': '6361.05', 'rank': None, 'percentile': 51.0, 'displayValue': '6,361.05'},
            {'label': 'Knock Outs', 'field': 'DBNOs', 'category': 'Support', 'ValueInt': 36, 'ValueDec': None,
             'value': '36', 'rank': None, 'percentile': 55.0, 'displayValue': '36'}]}], 'MatchHistory': [
        {'Id': 6746348, 'Updated': '2017-08-22T05:30:01.867', 'UpdatedJS': '1503379801867', 'Season': 3,
         'SeasonDisplay': 'Early Access Season #3', 'Match': 1, 'MatchDisplay': 'Solo', 'Region': 1,
         'RegionDisplay': '[NA] North America', 'Rounds': 1, 'Wins': 0, 'Kills': 0, 'Assists': 0, 'Top10': 0,
         'Rating': 1167.4, 'RatingChange': -6.7, 'RatingRank': 1819976, 'RatingRankChange': 62731, 'Headshots': 0,
         'Kd': 0.0, 'Damage': 41, 'TimeSurvived': 430.8, 'WinRating': 951, 'WinRank': 1894234, 'WinRatingChange': -4,
         'WinRatingRankChange': 31983, 'KillRating': 1080, 'KillRank': 479158, 'KillRatingChange': -14,
         'KillRatingRankChange': 58843, 'MoveDistance': 676.99},
        {'Id': 6630076, 'Updated': '2017-08-21T17:13:16.23', 'UpdatedJS': '1503335596230', 'Season': 3,
         'SeasonDisplay': 'Early Access Season #3', 'Match': 1, 'MatchDisplay': 'Solo', 'Region': 1,
         'RegionDisplay': '[NA] North America', 'Rounds': 1, 'Wins': 0, 'Kills': 6, 'Assists': 0, 'Top10': 0,
         'Rating': 1174.1, 'RatingChange': 16.2, 'RatingRank': 1757245, 'RatingRankChange': 102303, 'Headshots': 0,
         'Kd': 6.0, 'Damage': 656, 'TimeSurvived': 650.76, 'WinRating': 955, 'WinRank': 1862251, 'WinRatingChange': 6,
         'WinRatingRankChange': 177740, 'KillRating': 1094, 'KillRank': 420315, 'KillRatingChange': 54,
         'KillRatingRankChange': -226874, 'MoveDistance': 3699.87},
        {'Id': 6164562, 'Updated': '2017-08-20T02:57:40.58', 'UpdatedJS': '1503197860580', 'Season': 3,
         'SeasonDisplay': 'Early Access Season #3', 'Match': 1, 'MatchDisplay': 'Solo', 'Region': 1,
         'RegionDisplay': '[NA] North America', 'Rounds': 1, 'Wins': 0, 'Kills': 1, 'Assists': 0, 'Top10': 0,
         'Rating': 1157.9, 'RatingChange': -11.2, 'RatingRank': 1654942, 'RatingRankChange': 64384, 'Headshots': 0,
         'Kd': 1.0, 'Damage': 176, 'TimeSurvived': 155.79, 'WinRating': 949, 'WinRank': 1684511, 'WinRatingChange': -12,
         'WinRatingRankChange': 43802, 'KillRating': 1040, 'KillRank': 647189, 'KillRatingChange': 5,
         'KillRatingRankChange': -27914, 'MoveDistance': 198.47},
        {'Id': 6093538, 'Updated': '2017-08-19T19:02:29.64', 'UpdatedJS': '1503169349640', 'Season': 3,
         'SeasonDisplay': 'Early Access Season #3', 'Match': 2, 'MatchDisplay': 'Duo', 'Region': 1,
         'RegionDisplay': '[NA] North America', 'Rounds': 6, 'Wins': 0, 'Kills': 10, 'Assists': 6, 'Top10': 2,
         'Rating': 1304.3, 'RatingChange': 1304.3, 'RatingRank': 393074, 'RatingRankChange': 393074, 'Headshots': 0,
         'Kd': 1.67, 'Damage': 1472, 'TimeSurvived': 6625.05, 'WinRating': 1085, 'WinRank': 400253,
         'WinRatingChange': 1085,
         'WinRatingRankChange': 400253, 'KillRating': 1092, 'KillRank': 359071, 'KillRatingChange': 1092,
         'KillRatingRankChange': 359071, 'MoveDistance': 27889.1}]}
